[package]
name = "picoos"
version = "0.1.0"
authors = ["Paul Scharnofske <asynts@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
lto = true
codegen-units = 1
